name: Docker Image CI

on:
  push:
    branches:
      - "master"
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */6 * * *'

jobs:

  build-push:
    runs-on: ubuntu-latest

    steps:

    # arm64 specific
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # arm64 specific

    - name: Check Out Repo
      uses: actions/checkout@v2
    
    - name: login into github package registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ghcr.io/shindouj/libremdb:latest
        build-args: release=1
